package com.borracharia.borracharia.dto.Response;

import java.math.BigDecimal;
import java.time.LocalDate;

public record ProdutoResponseDTO(
    Long id,
    String codigoProduto,
    String codigoFabricante,
    String descricao,
    String complemento,
    String marca,
    String outrosInfo,
    String classe,
    BigDecimal embalagem,
    String unidade,
    BigDecimal quantidadeUnidade,
    String localizacao,
    BigDecimal precoProduto,
    BigDecimal frete,
    BigDecimal custoMedio,
    LocalDate ultimoReajuste,
    BigDecimal margemLucro,
    BigDecimal precoVenda,
    Integer quantidadeEstoque,
    Integer quantidadePedido,
    Integer quantidadeAguardando,
    Integer quantidadeMinima,
    String codigoComissao,
    BigDecimal peso,
    BigDecimal ipiPercentual,
    BigDecimal diferencaIcmsPercentual,
    BigDecimal outrosPercentual,
    BigDecimal icmsPercentual,
    BigDecimal reducaoIcmsPercentual,
    BigDecimal icmsSubstituicaoPercentual,
    BigDecimal ipiPercentualFinal,
    String checarEstoque
) {}